name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  call-basic-validation:
    name: Basic validation
    #uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main
    uses: IvanZosimov/reusable-workflows/.github/workflows/basic-validation.yml@main